// ReSharper disable RedundantUsingDirective.Global
global using PoeShared.Audio.ViewModels;
global using PoeShared.Scaffolding.WPF;
global using PoeShared.UI.Bindings;
global using PoeShared.Wpf.Scaffolding;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using PoeShared;
global using PoeShared.Modularity;
global using PoeShared.Native;
global using PoeShared.Scaffolding; 
global using PoeShared.Logging;
global using System;
global using System.Reactive;
global using System.Reactive.Concurrency;
global using System.Reactive.Linq;
global using System.Reactive.Subjects;
global using System.Threading;
global using System.Reactive.Disposables;
global using System.Linq.Expressions;
global using System.Collections.ObjectModel;
global using System.Collections.Concurrent;
global using System.Reactive.Threading.Tasks;
global using System.Threading.Tasks;
global using JetBrains.Annotations;
global using PoeShared.Prism;
global using PoeShared.UI;
global using PoeShared.WindowSeekers;
global using PoeShared.Services;
global using ReactiveUI;
global using Unity;
global using System.IO;
global using PropertyBinder;
global using DynamicData;
global using DynamicData.Binding;
global using DynamicData.Kernel;
global using WinSize = System.Drawing.Size;
global using WinPoint = System.Drawing.Point;
global using WinRectangle = System.Drawing.Rectangle;
global using IDisposable = System.IDisposable;
global using Guard = PoeShared.Guard;
global using AwesomeIcons = PoeShared.Themes.AwesomeIcons;
global using Path = System.IO.Path;
global using Directory = System.IO.Directory;
global using SearchOption = System.IO.SearchOption;
global using File = System.IO.File;